# Generated by Django 3.2.10 on 2024-01-19 14:02

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_languagemodel_topicmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', djongo.models.fields.JSONField()),
                ('level', models.TextField()),
                ('mark', models.IntegerField()),
                ('time', models.FloatField()),
                ('languageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.languagemodel')),
                ('topicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.topicmodel')),
            ],
        ),
    ]
