# Generated by Django 4.1.13 on 2024-01-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_student_email_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
