# Generated by Django 4.1.13 on 2024-01-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_student_date_alter_student_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobileNumber',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='whatsappNumber',
            field=models.TextField(),
        ),
    ]
